#
#-- html template
#
#use these definitions to modify the html of the documentation pages
htmlcomments = '''
<!--
	generated by pacmanFunctionLister.py
	please make changes in definition files, not this one
-->'''
htmltitlestart = '''
<html>
<title>'''
htmltitleend = '''
</title>'''
htmlbodystart = '''
<body background="sky.gif">'''
htmlheaderstart = '''
<h1><font color=navy>'''
htmlheaderend = '''
</font></h1>'''
htmlmainpagestart = '''
<hr size=5>
<dl>'''

htmlgrpstart = '''
<p>
<dt>'''
htmlfncnstart =	'''<font color=navy>'''	#printed in front of every function, not just the whole group
htmlargsstart =	'''&nbsp;<i>'''		#printed in front of '(' of argument list
htmlargsend =	'''</i>'''		#printed after ')' of argument list
htmlfncnend =	'''</font>'''		#printed after every function, not just the whole group
htmlfncnseparator = ''', '''		#printed between functions, if there are multiple functions in a group
htmldscrptnstart = '''
</dt>
<dd>'''
htmldscrptnend = '''
</dd>
</p>'''

htmlmainpageend = '''
</dl>'''
htmlfooterstart = '''
<hr size=5>
<h3><a href="http://physics.bu.edu/pacman/" target="_blank">Pacman Headquarters</a></h3>'''
htmlfooterend = '''
'''
htmlbodyend = '''
</body>
</html>
'''

#special stuff for the complete alphabetical list html page
#may use above also, unless same thing is defined here with _index_ in name
html_index_title = 'Pacman Functions'
html_index_header = 'The complete list of Pacman functions'
html_index_mainpagestart = '''
Click on a function name to see related functions and a description.
<br>
<hr size=5>'''
html_index_linkattributes = ''		#just the stytle attributes of the <a> tags; it will by <a id="itsid" name="itsname" html_index_linkattributes>function()</a>
html_index_fncndscrptnstart = '&nbsp;&nbsp;&nbsp;&nbsp;'	#only printed if the function has a description
html_index_fncndscrptnend = '<br>'	#only printed if the function has a description

#other substitutions, etc
htmlfncnspecspacereplacement = '''&nbsp;'''
#the following are real hacks just to do some finishing touches; prone to breaking
html_individual_top = {}		#after htmlmainpagestart
html_individual_bottom = {}		#before htmlmainpageend
html_individual_bottom['version'] = '''
<p>
If you want to test versions of software not in this list, a good option is to use <a href="Shells.html">shellOutput, shellOutputLE</b></a>, etc.
<p>'''
